### ISSUE TITLE
difference from original vitpose

### ISSUE THREAD

**Issue by hamza3e** [gpastal24/ViTPose-Pytorch#3] opened 2022-11-07 00:48 UTC
Hi, is there any difference between the original vitpose architecture? I get different result for same frame when I run on https://huggingface.co/spaces/Gradio-Blocks/ViTPose . Do you thing it might be about image correction part?

**Comment by gpastal24** [comment] 2022-11-07 06:49
Hi is it better or worse, could you share the 2 frames side by side?

**Comment by hamza3e** [comment] 2022-11-07 07:09
vitpose - 
![vitpose-result](https://user-images.githubusercontent.com/40697018/200246252-4b6d5d7b-fdc5-4b1f-ad0b-33dbfd20492e.png)

vitpose-pytorch - 
![vitpose-pytorch-result](https://user-images.githubusercontent.com/40697018/200246343-69ffb794-b924-4610-a118-f85c84bbaa95.png)

**Comment by gpastal24** [comment] 2022-11-07 08:28
thanks i will look into it , but I think you are correct. The correction factor part would be the culprit in this case. 
Did you use the pose_points_yolo5 to obtain the keypoints or did you do something else?

Hi again, I tested the second image with this function. Yolo doesn't seem to detect the person (not even the yolov5x).
These are the results for a sample image from hugging face.

hugging face
![index](https://user-images.githubusercontent.com/104021640/200269030-0679555f-b39e-41f0-9c23-98c2a4469fb3.png)

This repo
![test_out](https://user-images.githubusercontent.com/104021640/200269049-0a1f94aa-72f4-46c3-9b8b-a3733956197c.png)

**Comment by hamza3e** [comment] 2022-11-07 14:34
I use Yolov7-e6e model to detect persons. Then I use the vitpose-pytorch part to detect joints. I find bboxes are so similar with the hugging face replicate. How do you find the correction part of your code? I will try to understand the difference between original vitpose repo.

**Comment by gpastal24** [comment] 2022-11-07 16:15
> I use Yolov7-e6e model to detect persons. Then I use the vitpose-pytorch part to detect joints. I find bboxes are so similar with the hugging face replicate. How do you find the correction part of your code? I will try to understand the difference between original vitpose repo.

Hi I think I have fixed it will update the repo sortly. It had to do with the correction factor when the x  was much larger than y and y2 was close to the image border
![test_out](https://user-images.githubusercontent.com/104021640/200359720-de2f8fe2-b795-4ec9-8dc3-bdae15ea9254.png)

**Comment by gpastal24** [comment] 2022-11-07 16:42
Can you check now?

FYI the lines of code that do the aspect ratio correction are the following.
https://github.com/gpastal24/ViTPose-Pytorch/blob/b400e3d7ff32bfbee1dcb4b045d243aaa7fab007/pose_utils.py#L93-L132

**Comment by hamza3e** [comment] 2022-11-07 17:13
wow that is awesome. thank you very much. It works now

**Comment by gpastal24** [comment] 2022-11-07 17:32
If everything works as intended feel free to close this issue.

**Closed as completed** 2022-11-07 17:38 UTC
